name: Build

on: [push, repository_dispatch, workflow_dispatch]

jobs:

  
  build-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zcaudate/testing-foundation:main
      
    strategy:
      matrix:
        downstream: ['statstrade-dev/ci']
      
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Installing base jars
        run: |
          cd foundation-base && lein install
          
      - name: Checkout fx repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Installing fx jars
        run: |
          cd foundation-fx && lein install
          
      - name: Checkout embed repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-embed
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Installing embed jars
        run: lein install
        
      - name: Copy .m2 to docker
        run:  cp -r /root/.m2 docker/.m2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate/foundation-ci

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          push: true
          
      - name: Notify downstream
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ matrix.downstream }}
          event-type: foundation-changed
          client-payload: '{"repo": "${{ github.repository.id }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "comment": "${{ github.payload.comment }}"}'

  incomplete-base:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: List base incomplete
        run: > 
          docker run --network host 
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd) 
          -w $(pwd) 
          ghcr.io/zcaudate/testing-foundation:main lein incomplete

  incomplete-embed:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Checkout embed repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }} 
          
      - name: List embed incomplete
        run: > 
          docker run --network host 
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd)
          -w $(pwd) ghcr.io/zcaudate/testing-foundation:main 
          bash -c 'cd foundation-base && lein install && cd ../foundation-embed && lein incomplete'

  incomplete-fx:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Checkout fx repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }} 
          
      - name: List fx incomplete
        run: > 
          docker run --network host 
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd)
          -w $(pwd) ghcr.io/zcaudate/testing-foundation:main 
          bash -c 'cd foundation-base && lein install && cd ../foundation-fx && lein incomplete'
   
   
          
