name: Build

on: [push, repository_dispatch, workflow_dispatch]

jobs:

  build-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zcaudate/testing-foundation:main
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Installing Jars
        run: |
          cd foundation-base && lein install
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-embed
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Installing Jars
        run: lein install
        
      - name: Copy Jars
        run:  cp -r /root/.m2 docker/.m2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate/foundation-embed

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          push: true
