name: Run Tests

on: push

jobs:
  run-base-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Running Tests
        run: docker run --network host -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):$(pwd) -w $(pwd) ghcr.io/zcaudate/testing-foundation:main lein test
        
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test-scratch
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
          
  run-embed-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Checkout embed repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }} 
          
      - name: Running embed tests
        run: > 
          cd foundation-embed && docker run --network host 
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd)
          -w $(pwd) ghcr.io/zcaudate/testing-foundation:main 
          bash -c 'cd foundation-base && lein install && cd ../foundation-embed && lein test'
   
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test-scratch
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
